version: "3.9"
services:
  go116:
    build:
      context: .
      dockerfile: docker/go116/dockerfile
    volumes:
      - .:/app
    environment: 
      # PostgreSQL settings
      JOBSD_PG_HOST: postgres
      JOBSD_PG_PORT: 5432
      JOBSD_PG_PASSWORD: jobsd
      JOBSD_PG_USER: jobsd
      JOBSD_PG_DB: jobsd
      # MySQL settings
      JOBSD_MY_HOST: mysql
      JOBSD_MY_PORT: 3306
      JOBSD_MY_DB: jobsd
      JOBSD_MY_USER: jobsd
      JOBSD_MY_PASSWORD: jobsd
  postgres:
    image: postgres:latest
    ports:
      - "25432:5432"
    environment: 
      POSTGRES_PASSWORD: jobsd
      POSTGRES_USER: jobsd
      POSTGRES_DB: jobsd
  mysql:
    image: 'mysql:latest'
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE=jobsd
      MYSQL_USER=jobsd
      MYSQL_PASSWORD=jobsd
      MYSQL_RANDOM_ROOT_PASSWORD="yes"
